<div id="project-menu" class="menu">
	<ul>
		<li><a href="http://csug.rochester.edu/u/elin9/whitebored.html" target="_blank">WhiteBored</a></li>
		<li><a href="shutterstock_intern.php">Shutterstock Internship</a></li>
		<li><a href="rhema.php">RHEMA</a></li>
		<li><a href="https://sites.google.com/site/rochciteammia" target="_blank">HCI Class Project</a></li>
		<li><a href="http://emy-lin.rochestercs.org/project3/index.php" target="_blank">Web Design Class Project</a></li>
	</ul>
</div>